// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHHaTsOh_sKiw_ERv2zWqcfdxtDm2YDXI',
    appId: '1:1051879808183:web:4d006d748fd92a8289c132',
    messagingSenderId: '1051879808183',
    projectId: 'gpc-proyect',
    authDomain: 'gpc-proyect.firebaseapp.com',
    storageBucket: 'gpc-proyect.firebasestorage.app',
    measurementId: 'G-643DE38CY5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgrrIkuArdnV2SbOqst1xImUgfywilbbY',
    appId: '1:1051879808183:android:7f0f28fd68ce6bb189c132',
    messagingSenderId: '1051879808183',
    projectId: 'gpc-proyect',
    storageBucket: 'gpc-proyect.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQOTu1YxI8RkxcmDLCqbtIu0lnKbJLiH0',
    appId: '1:1051879808183:ios:842b54286e1d0b2989c132',
    messagingSenderId: '1051879808183',
    projectId: 'gpc-proyect',
    storageBucket: 'gpc-proyect.firebasestorage.app',
    iosBundleId: 'com.example.appmovil',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQOTu1YxI8RkxcmDLCqbtIu0lnKbJLiH0',
    appId: '1:1051879808183:ios:842b54286e1d0b2989c132',
    messagingSenderId: '1051879808183',
    projectId: 'gpc-proyect',
    storageBucket: 'gpc-proyect.firebasestorage.app',
    iosBundleId: 'com.example.appmovil',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHHaTsOh_sKiw_ERv2zWqcfdxtDm2YDXI',
    appId: '1:1051879808183:web:c02f286c6607f8f289c132',
    messagingSenderId: '1051879808183',
    projectId: 'gpc-proyect',
    authDomain: 'gpc-proyect.firebaseapp.com',
    storageBucket: 'gpc-proyect.firebasestorage.app',
    measurementId: 'G-S3LXS5QSDF',
  );
}
